// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNN9bJYCmvkneH83-stzlVcyZfGaDDVyE',
    appId: '1:204722986911:web:c7cf551739368a8c8fa7aa',
    messagingSenderId: '204722986911',
    projectId: 'ntu-ventes-app',
    authDomain: 'ntu-ventes-app.firebaseapp.com',
    storageBucket: 'ntu-ventes-app.appspot.com',
    measurementId: 'G-E38VHPD7JS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4W6PqDsp5znWYY_WMmJcjNoddPPlAE2o',
    appId: '1:204722986911:android:d14e537b626c541b8fa7aa',
    messagingSenderId: '204722986911',
    projectId: 'ntu-ventes-app',
    storageBucket: 'ntu-ventes-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBywecEy8qeVSysCLfaYqAjwTfIyiYfryY',
    appId: '1:204722986911:ios:5db5e4772c77d6ad8fa7aa',
    messagingSenderId: '204722986911',
    projectId: 'ntu-ventes-app',
    storageBucket: 'ntu-ventes-app.appspot.com',
    iosClientId: '204722986911-glgs9802cgmi59up89ju5e9dosrd5iks.apps.googleusercontent.com',
    iosBundleId: 'com.example.ventes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBywecEy8qeVSysCLfaYqAjwTfIyiYfryY',
    appId: '1:204722986911:ios:5db5e4772c77d6ad8fa7aa',
    messagingSenderId: '204722986911',
    projectId: 'ntu-ventes-app',
    storageBucket: 'ntu-ventes-app.appspot.com',
    iosClientId: '204722986911-glgs9802cgmi59up89ju5e9dosrd5iks.apps.googleusercontent.com',
    iosBundleId: 'com.example.ventes',
  );
}
